import { translate } from "core/config/i18n";
import { Menu } from "./config-type";
import {
  ACCEPTANCE_ROUTE,
  AREA_UNIT_CODE_ROUTE,
  BAND_ROUTE,
  BANK_ROUTE,
  BUDGET_MANAGEMENT_ROUTE,
  BUDGET_ROUTE,
  BUSINESS_BRANCH_ROUTE,
  BUSINESS_DEPARTMENT_ROUTE,
  CATALOG_ROUTE,
  CENTRAL_PURCHASE_UNIT_ROUTE,
  COMMENT_MANAGEMENT_ROUTE,
  CONTRACT_CLASSIFICATION_ROUTE,
  CONTRACT_MANAGEMENT_ROUTE,
  CONTRACT_METHOD_ROUTE,
  CONTRACT_PRINCIPLE_ROUTE,
  CONTRACT_ROUTE,
  CONTRACT_TERM_ROUTE,
  CONTRACT_TERMINATION_ROUTE,
  COST_DRIVER_ROUTE,
  COST_ITEM_GOODS_SERVICES_ROUTE,
  COST_ITEM_ROUTE,
  COST_LINE_COST_ITEM_ROUTE,
  COST_LINE_ROUTE,
  COST_TYPE_ROUTE,
  CURRENCY_ROUTE,
  DASHBROAD_ROUTE,
  DOCUMENT_TYPE_ROUTE_MASTER,
  EXCHANGE_RATE_ROUTE,
  FINANCIAL_INFORMATION_MANAGEMENT_ROUTE,
  GL_ACCOUNT_ROUTE,
  GOOD_SERVICE_TYPE_ROUTE,
  GOODS_MANAGEMENT_ROUTE,
  GOODS_SERVICE_CATEGORY_ROUTE,
  GOODS_SERVICES_ROUTE,
  GUARANTEE_TYPE_ROUTE_MASTER,
  LEGAL_ENTITY_ROUTE_MASTER,
  MANUFACTURER_CATEGORIES_ROUTE,
  NATION_ROUTE,
  ORGANIZATION_MANAGEMENT_ROUTE,
  OTHERS_MANAGEMENT_ROUTE,
  PAYMENT_CONDITION_ROUTE,
  PAYMENT_ROUTE,
  PERSONNEL_BY_UNIT_ROUTE,
  POSITION_ROUTE,
  PROJECT_SETTLEMENT_ROUTE,
  PROMOTION_ROUTE,
  PROPOSAL_ROUTE,
  PURCHASE_REQUEST_ROUTE,
  PURCHASE_ROUTE,
  PURCHASING_PLAN_ROUTE,
  RANK_ROUTE,
  RECEIVING_GOODS_ROUTE,
  REPORT_BUDGET_CONTROL_ROUTER,
  REPORT_BUDGET_ROUTER,
  REPORT_BUDGET_USAGE_ROUTER,
  REPORT_DETAILED_SUPPLIER_PAYABLES_ROUTER,
  REPORT_GOODS_RECEIPT_TRACKING_ROUTER,
  REPORT_INVESTMENT_PROJECT_PORTFOLIO_ROUTER,
  REPORT_ORDER_CHANGE_SUPPLIER_INFO_ROUTER,
  REPORT_ORDER_CONTRACT_DEBT_DETAIL_ROUTER,
  REPORT_ORDER_GOOD_SERVICE_DETAIL_ROUTER,
  REPORT_ORDER_TRANSACTION_DAILY_ROUTER,
  REPORT_PAYMENT_BY_APPROVAL_AUTHORITY_ROUTER,
  REPORT_PAYMENT_BY_COST_ITEM_ROUTER,
  REPORT_PAYMENT_BY_PROMO_ROUTER,
  REPORT_PAYMENT_ROUTER,
  REPORT_PROPOSAL_SUMMARY_ROUTER,
  REPORT_PURCHASE_DETAIL_ROUTER,
  REPORT_PURCHASE_ORDER_DETAIL_ROUTER,
  REPORT_PURCHASE_ORDER_ROUTER,
  REPORT_PURCHASE_REQUIREMENT_SUMMARY_ROUTER,
  REPORT_PURCHASE_ROUTER,
  REPORT_PURCHASE_SUMMARY_ROUTER,
  REPORT_ROUTE,
  REPORT_SLA_ROUTER,
  REPORT_SUPPLIER_GOODS_DETAIL_ROUTER,
  REPORT_TEMPLATE_MANAGEMENT_ROUTE,
  SETTLEMENT_ROUTE,
  SIGNATURE_CONFIG_ROUTE,
  SIGNATURE_MANAGEMENT_ROUTE,
  SIGNATURE_SUPPLIER_ROUTE,
  SPECIALIZED_BANK_ROUTE,
  SUPPLIER_CATEGORY_CONFIG_ROUTE,
  SUPPLIER_EVALUATION_CONFIG_ROUTE,
  SUPPLIER_MANAGEMENT_ROUTE,
  SUPPLIER_ROUTE,
  SUPPLIER_TYPE_ROUTE,
  SYSTEM_ADMINISTRATION_ROUTE,
  TAX_ROUTE,
  TEMPORARY_IMPORT_ASSET_MASTER_ROUTE,
  UNIT_OF_MEASURE_GROUP_ROUTE,
  UNIT_OF_MEASURE_ROUTE,
  USE_ELECTRONIC_INVOICE_ROUTE,
  WARRANTY_METHOD_ROUTE_MASTER,
  WARRANTY_TYPE_ROUTE_MASTER,
} from "./route-const";
import { MENU_CODE } from "./const";

const menuCatalog = [
  // 1 organization management
  {
    name: translate("CM.menu_title_organization_management"),
    link: ORGANIZATION_MANAGEMENT_ROUTE,
    // code: "NONE_PERMISSION",
    show: true,
    active: false,
    children: [
      {
        name: translate("CM.menu_title_specialized_bank"),
        link: SPECIALIZED_BANK_ROUTE,
        code: MENU_CODE.CATALOG_BUSINESS_UNIT,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_business_department"),
        link: BUSINESS_DEPARTMENT_ROUTE,
        code: MENU_CODE.CATALOG_BUSINESS_DEPARTMENT,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_business_branch"),
        link: BUSINESS_BRANCH_ROUTE,
        code: MENU_CODE.CATALOG_BUSINESS_BRANCH,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_rank"),
        link: RANK_ROUTE,
        code: MENU_CODE.CATALOG_RANK,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_band"),
        link: BAND_ROUTE,
        code: MENU_CODE.CATALOG_BAND,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_position"),
        link: POSITION_ROUTE,
        code: MENU_CODE.CATALOG_POSITION,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_central_purchase_unit"),
        link: CENTRAL_PURCHASE_UNIT_ROUTE,
        code: MENU_CODE.CATALOG_CENTRALIZED_PURCHASING_UNIT,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_area_unit_code"),
        link: AREA_UNIT_CODE_ROUTE,
        code: MENU_CODE.CATALOG_COSTCENTERALLOCATION,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_personnel_by_unit"),
        link: PERSONNEL_BY_UNIT_ROUTE,
        code: MENU_CODE.CATALOG_PERSONNEL_BY_UNIT,
        show: true,
        active: false,
      },
    ],
  },
  // 2 budget management
  {
    name: translate("CM.menu_title_budget_management"),
    link: BUDGET_MANAGEMENT_ROUTE,
    show: true,
    active: false,
    children: [
      {
        name: translate("CM.menu_title_cost_line"),
        link: COST_LINE_ROUTE,
        code: MENU_CODE.CATALOG_COSTLINE,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_cost_driver"),
        link: COST_DRIVER_ROUTE,
        code: MENU_CODE.CATALOG_COST_DRIVER,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_cost_type"),
        link: COST_TYPE_ROUTE,
        code: MENU_CODE.CATALOG_COST_TYPE,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_cost_item"),
        link: COST_ITEM_ROUTE,
        code: MENU_CODE.CATALOG_COSTITEM,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_cost_line_cost_item"),
        link: COST_LINE_COST_ITEM_ROUTE,
        code: MENU_CODE.CATALOG_COSTLINE_COSTGROUP_CONFIG,
        show: true,
        active: false,
      },
    ],
  },
  // 3 financial infomation management
  {
    name: translate("CM.menu_title_financial_infomation_management"),
    link: FINANCIAL_INFORMATION_MANAGEMENT_ROUTE,
    show: true,
    active: false,
    children: [
      {
        name: translate("CM.menu_title_bank"),
        link: BANK_ROUTE,
        code: MENU_CODE.CATALOG_BANK,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_currency"),
        link: CURRENCY_ROUTE,
        code: MENU_CODE.CATALOG_CURRENCY,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_exchange_rate"),
        link: EXCHANGE_RATE_ROUTE,
        code: MENU_CODE.CATALOG_RATEOFEXCHANGE,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_tax"),
        link: TAX_ROUTE,
        code: MENU_CODE.CATALOG_TAX,
        show: true,
        active: false,
      },
    ],
  },
  // 4 supplier management
  {
    name: translate("CM.menu_title_supplier_management"),
    link: SUPPLIER_MANAGEMENT_ROUTE,
    // code: "NONE_PERMISSION",
    show: true,
    active: false,
    children: [
      {
        name: translate("CM.menu_title_supplier"),
        link: SUPPLIER_ROUTE,
        code: MENU_CODE.CATALOG_MANAGE_SUPPLIER,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_supplier_type"),
        link: SUPPLIER_TYPE_ROUTE,
        code: MENU_CODE.CATALOG_SUPPLIER_TYPE,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_supplier_category_config"),
        link: SUPPLIER_CATEGORY_CONFIG_ROUTE,
        code: MENU_CODE.CATALOG_SUPPLIER_CATEGORY_CONFIG,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_supplier_evaluation"),
        link: SUPPLIER_EVALUATION_CONFIG_ROUTE,
        code: MENU_CODE.CATALOG_SUPPLIER_EVALUATION_CONFIG,
        show: true,
        active: false,
      },
    ],
  },
  // 5 goods management
  {
    name: translate("CM.menu_title_goods_management"),
    link: GOODS_MANAGEMENT_ROUTE,
    show: true,
    active: false,
    children: [
      {
        name: translate("CM.menu_title_catalog_good_service"),
        link: GOODS_SERVICES_ROUTE,
        code: MENU_CODE.CATALOG_GOODS_SERVICE,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_good_service_type"),
        link: GOOD_SERVICE_TYPE_ROUTE,
        code: MENU_CODE.CATALOG_GOODSERVICETYPE,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_unit_of_measure"),
        link: UNIT_OF_MEASURE_ROUTE,
        code: MENU_CODE.CATALOG_UNIT_OF_MEASURE,
        show: true,
        active: false,
      },

      {
        name: translate("CM.menu_title_catalog_unit_of_measure_group"),
        link: UNIT_OF_MEASURE_GROUP_ROUTE,
        code: MENU_CODE.CATALOG_UNIT_OF_MEASURE_GROUP,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_good_service_category"),
        link: GOODS_SERVICE_CATEGORY_ROUTE,
        code: MENU_CODE.CATALOG_GOODS_SERVICES_CATEGORY,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_manufacturer_categories"),
        link: MANUFACTURER_CATEGORIES_ROUTE,
        code: MENU_CODE.CATALOG_MANUFACTURERS,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_cost_item_goods_services"),
        link: COST_ITEM_GOODS_SERVICES_ROUTE,
        code: MENU_CODE.CATALOG_GOODS_SERVICE_COSTGROUP_CONFIG,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_payment_condition"),
        link: PAYMENT_CONDITION_ROUTE,
        code: MENU_CODE.CATALOG_PAYMENT_CONDITION,
        show: true,
        active: false,
      },
    ],
  },

  // 6 contract management
  {
    name: translate("CM.menu_title_contract_management"),
    link: CONTRACT_MANAGEMENT_ROUTE,
    show: true,
    active: false,
    children: [
      {
        name: translate("CM.menu_title_contract_method"),
        link: CONTRACT_METHOD_ROUTE,
        code: MENU_CODE.CATALOG_CONTRACT_METHOD,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_contract_term"),
        link: CONTRACT_TERM_ROUTE,
        code: MENU_CODE.CATALOG_CONTRACT_TERM,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_contract_classification"),
        link: CONTRACT_CLASSIFICATION_ROUTE,
        code: MENU_CODE.CATALOG_CONTRACT_TYPE,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_warranty_type"),
        link: WARRANTY_TYPE_ROUTE_MASTER,
        code: MENU_CODE.CATALOG_WARRANTY_TYPE,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_guarantee_type"),
        link: GUARANTEE_TYPE_ROUTE_MASTER,
        code: MENU_CODE.CATALOG_GUARANTEE_TYPE,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_warranty_method"),
        link: WARRANTY_METHOD_ROUTE_MASTER,
        code: MENU_CODE.CATALOG_WARRANTY_METHOD,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_legal_entity"),
        link: LEGAL_ENTITY_ROUTE_MASTER,
        code: MENU_CODE.CATALOG_LEGAL_ENTITY,
        show: true,
        active: false,
      },
    ],
  },
  // 6 other management
  {
    name: translate("CM.menu_title_other_management"),
    link: OTHERS_MANAGEMENT_ROUTE,
    show: true,
    active: false,
    children: [
      {
        name: translate("CM.menu_title_nation"),
        link: NATION_ROUTE,
        show: true,
        code: MENU_CODE.CATALOG_NATION,
        active: false,
      },
      {
        name: translate("CM.menu_title_use_electronic_invoice"),
        link: USE_ELECTRONIC_INVOICE_ROUTE,
        show: true,
        code: MENU_CODE.CATALOG_INVOICE,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_document_type"),
        link: DOCUMENT_TYPE_ROUTE_MASTER,
        code: MENU_CODE.CATALOG_DOCUMENT_TYPE,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_glAccount"),
        link: GL_ACCOUNT_ROUTE,
        code: MENU_CODE.CATALOG_GL_ACCOUNT,
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_catalog_promotion"),
        link: PROMOTION_ROUTE,
        code: MENU_CODE.CATALOG_PROMOTION,
        show: true,
        active: false,
      },
    ],
  },
  {
    name: translate("CM.menu_title_signature_management"),
    link: SIGNATURE_MANAGEMENT_ROUTE,
    show: true,
    active: false,
    children: [
      {
        name: translate("CM.menu_title_signature_supplỉer"),
        link: SIGNATURE_SUPPLIER_ROUTE,
        show: true,
        code: MENU_CODE.CATALOG_SIGNATURE_SUPPLIER,
        active: false,
      },
      {
        name: translate("CM.menu_title_signature_config"),
        link: SIGNATURE_CONFIG_ROUTE,
        show: true,
        code: MENU_CODE.CATALOG_SIGNATURE_CONFIG,
        active: false,
      },
    ],
  },

  // Chuyển sang ADM
  // {
  //   name: translate("CM.menu_calc_param_config"),
  //   link: CALCULATOR_PARAM_CONFIG_ROUTE,
  //   show: true,
  //   active: false,
  // },

  // Bỏ đi
  // {
  //   name: translate("CM.menu_title_catalog_commercial_terms"),
  //   link: COMMERCIAL_TERMS_ROUTE_MASTER,
  //   show: true,
  //   active: false,
  // },
];

export const menu: Menu[] = [
  {
    name: translate("CM.menu_title_home"),
    link: DASHBROAD_ROUTE,
    code: "HOME",
    show: true,
    active: false,
  },
  {
    name: translate("CM.menu_title_budget"),
    link: BUDGET_ROUTE,
    code: "PKG",
    show: true,
    active: false,
  },

  {
    name: translate("CM.menu_title_procurement"),
    link: PURCHASE_ROUTE,
    show: true,
    code: "PURCHASE",
    active: false,
    children: [
      {
        name: translate("CM.menu_title_proposal"),
        link: PROPOSAL_ROUTE,
        code: "PURCHASE_PROPOSAL",
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_purchase_request"),
        link: PURCHASE_REQUEST_ROUTE,
        code: "PURCHASE_REQUEST",
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_purchasing_plan"),
        link: PURCHASING_PLAN_ROUTE,
        code: "PURCHASE_PLAN",
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_contract_principle"),
        link: CONTRACT_PRINCIPLE_ROUTE,
        code: "PURCHASE_PRINCIPLE_CONTRACT",
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_contract"),
        link: CONTRACT_ROUTE,
        code: "PURCHASE_CONTRACT",
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_receiving_goods"),
        link: RECEIVING_GOODS_ROUTE,
        code: "PURCHASE_GOODS_RECEIPT",
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_acceptance"),
        link: ACCEPTANCE_ROUTE,
        code: "PURCHASE_ACCEPTANCE",
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_temporary_import_asset"),
        link: TEMPORARY_IMPORT_ASSET_MASTER_ROUTE,
        code: "PURCHASE_TEMP_RECEIPT",
        show: true,
        active: false,
      },

      {
        name: translate("CM.menu_title_settlement"),
        link: SETTLEMENT_ROUTE,
        code: "PURCHASE_CONTRACT_SETTLEMENT",
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_project_settlement"),
        link: PROJECT_SETTLEMENT_ROUTE,
        code: "PURCHASE_PROJECT_SETTLEMENT",
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_contract_liquidation"),
        link: CONTRACT_TERMINATION_ROUTE,
        code: "PURCHASE_CONTRACT_LIQUIDATION",
        show: true,
        active: false,
      },
    ],
  },

  {
    name: translate("CM.menu_title_payment"),
    link: PAYMENT_ROUTE,
    code: "PAYMENT",
    show: true,
    active: false,
  },

  {
    name: translate("CM.menu_title_report.master"),
    link: REPORT_ROUTE,
    code: "NONE_PERMISSION",
    show: true,
    active: false,
    children: [
      {
        name: translate("CM.menu_title_report.payment.master"),
        link: REPORT_PAYMENT_ROUTER,
        code: MENU_CODE.REPORT_PAYMENT,
        show: true,
        active: false,
        children: [
          {
            name: translate("CM.menu_title_report.payment.cost_items"),
            link: REPORT_PAYMENT_BY_COST_ITEM_ROUTER,
            code: MENU_CODE.REPORT_PAYMENT_BY_COSTGROUP,
            show: true,
            active: false,
          },
          {
            name: translate("CM.menu_title_report.payment.promo"),
            link: REPORT_PAYMENT_BY_PROMO_ROUTER,
            code: MENU_CODE.REPORT_PAYMENT_BY_PROMOTION,
            show: true,
            active: false,
          },
          {
            name: translate("CM.menu_title_report.payment.approval_authority"),
            link: REPORT_PAYMENT_BY_APPROVAL_AUTHORITY_ROUTER,
            code: MENU_CODE.REPORT_PAYMENT_BY_APPROVAL_AUTHORITY,
            show: true,
            active: false,
          },
        ],
      },
      {
        name: translate("CM.menu_title_report.budget.master"),
        link: REPORT_BUDGET_ROUTER,
        code: MENU_CODE.REPORT_BUDGET,
        show: true,
        active: false,
        children: [
          {
            name: translate("CM.menu_title_report.budget.usage"),
            link: REPORT_BUDGET_USAGE_ROUTER,
            code: MENU_CODE.REPORT_BUDGET_USAGE_MASTER,
            show: true,
            active: false,
          },
          {
            name: translate("CM.menu_title_report.budget.control"),
            link: REPORT_BUDGET_CONTROL_ROUTER,
            code: MENU_CODE.REPORT_BUDGET_CONTROL_MASTER,
            show: true,
            active: false,
          },
          {
            name: translate("report.budget.investment_project_portfolio.title"),
            link: REPORT_INVESTMENT_PROJECT_PORTFOLIO_ROUTER,
            code: MENU_CODE.REPORT_INVESTMENT_PROJECT_PORTFOLIO_MASTER,
            show: true,
            active: false,
          },
        ],
      },
      {
        name: translate("CM.menu_title_report.purchase.master"),
        link: REPORT_PURCHASE_ROUTER,
        code: MENU_CODE.REPORT_PURCHASE,
        show: true,
        active: false,
        children: [
          {
            name: translate(
              "CM.menu_title_report.purchase.purchase_plan_summary"
            ),
            link: REPORT_PURCHASE_SUMMARY_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_PLAN_SUMMARY,
            show: true,
            active: false,
          },
          {
            name: translate(
              "CM.menu_title_report.purchase.purchase_plan_detail"
            ),
            link: REPORT_PURCHASE_DETAIL_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_PLAN_DETAIL,
            show: true,
            active: false,
          },
          {
            name: translate("report.purchase.order_contract_summary.title"),
            link: REPORT_PURCHASE_ORDER_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_ORDER_CONTRACT_MASTER,
            show: true,
            active: false,
          },
          {
            name: translate(
              "report.purchase.order_contract_summary.title_detail"
            ),
            link: REPORT_PURCHASE_ORDER_DETAIL_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_ORDER_CONTRACT_DETAIL,
            show: true,
            active: false,
          },
          {
            name: translate(
              "CM.menu_title_report.purchase.supplier_goodsItem_detail"
            ),
            link: REPORT_SUPPLIER_GOODS_DETAIL_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_GOODS_SERVICE_OF_CONTRACT_DETAIL,
            show: true,
            active: false,
          },
          {
            name: translate("report.purchase.goods_receipt_tracking.title"),
            link: REPORT_GOODS_RECEIPT_TRACKING_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_TRACKING_DELIVERY_GOODS_SERVICE,
            show: true,
            active: false,
          },
          {
            name: translate(
              "CM.menu_title_report.purchase.contract_debt_details"
            ),
            link: REPORT_ORDER_CONTRACT_DEBT_DETAIL_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_DEBT_OF_CONTRACT_DETAIL,
            show: true,
            active: false,
          },
          {
            name: translate(
              "CM.menu_title_report.purchase.change_supplier_info"
            ),
            link: REPORT_ORDER_CHANGE_SUPPLIER_INFO_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_CHANGE_SUPPLIER_INFO,
            show: true,
            active: false,
          },
          {
            name: translate(
              "CM.menu_title_report.purchase.goods_services_detail"
            ),
            link: REPORT_ORDER_GOOD_SERVICE_DETAIL_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_GOODS_SERVICE_DETAIL,
            show: true,
            active: false,
          },
          {
            name: translate("CM.menu_title_report.purchase.transaction_daily"),
            link: REPORT_ORDER_TRANSACTION_DAILY_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_DAILY_TRANSACTION,
            show: true,
            active: false,
          },
          {
            name: translate("report.purchase.detailed_supplier_payables.title"),
            link: REPORT_DETAILED_SUPPLIER_PAYABLES_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_DEBT_OF_SUPPLIER_DETAIL,
            show: true,
            active: false,
          },
          {
            name: translate(
              "report.purchase.purchase_requirement_summary.title"
            ),
            link: REPORT_PURCHASE_REQUIREMENT_SUMMARY_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_REQUEST_SUMMARY,
            show: true,
            active: false,
          },
          {
            name: translate("report.purchase.proposal_summary.title"),
            link: REPORT_PROPOSAL_SUMMARY_ROUTER,
            code: MENU_CODE.REPORT_PURCHASE_SUMMARY_PURCHASING_POLICY,
            show: true,
            active: false,
          },
          {
            name: translate("report.purchase.sla.title"),
            link: REPORT_SLA_ROUTER,
            code: MENU_CODE.SLA,
            show: true,
            active: false,
          },
        ],
      },
    ],
  },

  {
    name: translate("CM.menu_title_catalog"),
    link: CATALOG_ROUTE,
    code: "CATALOG",
    show: true,
    active: false,
    children: menuCatalog,
  },

  {
    name: translate("CM.menu_title_system_administration"),
    link: SYSTEM_ADMINISTRATION_ROUTE,
    code: "NONE_PERMISSION",
    show: true,
    active: false,
    children: [
      {
        name: translate("CM.menu_title_comment_management"),
        link: COMMENT_MANAGEMENT_ROUTE,
        code: "NONE_PERMISSION",
        show: true,
        active: false,
      },
      {
        name: translate("CM.menu_title_report_template_management"),
        link: REPORT_TEMPLATE_MANAGEMENT_ROUTE,
        code: "NONE_PERMISSION",
        show: true,
        active: false,
      },
    ],
  },
];
